### ISSUE TITLE
existence of any more historical data on subscribers?

### ISSUE THREAD

**Issue by ckingdev** [voussoir/reddit#16]
I tried to find contact info for you, but came up empty, my apologies. This is not a problem with the repo.

I'm working on a project where the data you collected and released on subscriber counts over time has been extremely useful. I've got the sqlite databases from all of the releases, but I was wondering whether you might have more measurements lying around. I only need the subreddit name/id, subscriber count, and the date it was collected. Any other data, even if it's not complete, would be very helpful- a part of what I'm working on is looking at the patterns in time of the growth in communities by various metrics. To that end, having as many repeated measures for a subreddit as possible is helpful.

Another related question is whether you would be interested in the dataset I derive from your releases- I have a postgres table collating the subscriber counts over time from each release. I'd be happy to provide a sql dump or sqlite db file and with a little bit of work I could clean up my python code to generate that db given a set of dbs from your code, so that anyone with that data could reproduce it.

Thanks for making this available, it's been a huge help. If you'd prefer to discuss via email I can get you mine.

**Comment by voussoir** [comment]
Hi Cammie,

I'm embarrassed to say that I don't have much more to provide in terms of of subscriber data. It was always something that I thought about improving upon but never did, which I regret. And the `last_scanned` column wasn't even added to the SB table until [a year ago](https://github.com/voussoir/reddit/blame/2a3356278fa59689ca76fe388eb915c33bd49b3d/SubredditBirthdays/sb.py#L52) so the older versions are probably not too reliable for building a timeline.

The only other thing I can think of is [this post](https://www.reddit.com/r/GoldTesting/comments/3bypzz/amageddon_tracking) where I had the sub counts for a handful of subreddits involved in the amageddon. That's only a single other data point though.

Have you contacted [redditmetrics](http://redditmetrics.com), [metareddit](http://www.metareddit.com) and [snoopsnoo](https://snoopsnoo.com) as well?

There is also this bigquery table called [subreddits_201509](https://bigquery.cloud.google.com/table/fh-bigquery:reddit.subreddits_201509) which I'm assuming is the work of Stuck_in_the_Matrix?

&nbsp;

Sure, I would be interested to see your final results. Don't worry about that automatic converter thing, at least not on my behalf. I'm sure working with my inconsistent schemas and this binary-bloated git repository has been enough of a pain as it is.

**Comment by voussoir** [comment]
Closing old issues.
