### ISSUE TITLE
All to Any

### ISSUE THREAD

**Issue by chandru9279** [voussoir/reddit#8]
https://github.com/voussoir/reddit/blob/master/ReplyBot/replybot.py#L82

Hi 

Instead of checking all are not equal, you can check any are equal. It should be more understandable then.
```
        if KEYAUTHORS != [] and all(auth.lower() != pauthor for auth in KEYAUTHORS):
            # This post was not made by a keyauthor
            continue
```

like

`not any(auth.lower() == pauthor for auth in KEYAUTHORS)`

**IMPORTANT**

You also need to `.lower()` on the RHS as follows

`not any(auth.lower() == pauthor.lower() for auth in KEYAUTHORS)`

as reddit returns in caps sometimes.

**Comment by voussoir** [comment]
Sounds good, I'll change it to `not any` in my next commit. And you're absolutely right about the lowercase, that was complete oversight on my part. In a previous version, I probably had `pauthor` set to lowercase at an earlier time, so I didn't need to do it in the keyauthor check.

**Comment by voussoir** [comment]
I forgot this issue was still open. Thanks again for pointing that out!
